---
name: 'Upload Gzip Artifact'
description: 'Tar a directory/file and compress it with gzip and upload the artifact.'
author: "Nicolas Merget"
branding:
  icon: package
  color: gray-dark
inputs:
  name:
    description: 'Name for the artifact'
    required: true
  path:
    description: 'Path to a directory or file to zip'
    required: true
  retention-days:
    description: ' Duration after which artifact will expire in days'
    required: false
    default: "5"
runs:
  using: 'composite'
  steps:
    - name: 📦 Pack as tar an compress
      run: tar -czf ${{ inputs.name }}.tar.gz ${{ inputs.path }}
      shell: bash

    - name: ⏫ Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.name }}
        path: ${{ inputs.name }}.tar.gz
        retention-days: ${{ inputs.retention-days }}

    - name: 🚮 Remove tar
      run: rm ${{ inputs.name }}.tar.gz
      shell: bash